### ISSUE TITLE
Consistently getting 404 not found while trying to create object....

### ISSUE THREAD

**Issue by sirvon** [Syncano/syncano-android#5]
I'm using this code to attempt to create an object on a class....

POJO

``` java
@SyncanoClass(name = "inapp")
public class InApp extends SyncanoObject{

    public static final String FIELD_EVENT = "eventt";

    @SyncanoField(name = FIELD_EVENT)
    public String event;

}
```

IMPL

``` java
....
  static Syncano syncano;

  syncano = new Syncano(BuildConfig.SYNCANO_KEY, BuildConfig.SYNCANO_GLOBAL_INSTANCE);

InApp inApp = new InApp();
        inApp.event = "event";
        Log.d(TAG,inApp.toString());

        Response<InApp> responseCreateObject = syncano.createObject(inApp).send();

        if (responseCreateObject.getResultCode() == Response.CODE_SUCCESS) {
            slackApi.call(new SlackMessage(String.valueOf(Response.CODE_SUCCESS)));
        } else if (responseCreateObject.getResultCode() == Response.CODE_HTTP_ERROR) {
            Log.d(TAG, "Result Code: " + responseCreateObject.getHttpResultCode());
            Log.d(TAG, "Reason Phrase: " + responseCreateObject.getHttpReasonPhrase());
            slackApi.call(new SlackMessage(String.valueOf(responseCreateObject.getHttpResultCode())));
            slackApi.call(new SlackMessage(String.valueOf(responseCreateObject.getHttpReasonPhrase())));
        }
```

``` java
10-22 20:17:35.475 31011-31347/com.xxxx D/xxx: Result Code: 404
10-22 20:17:35.475 31011-31347/com.xxxx D/xxx: Reason Phrase: NOT FOUND
```

The class exist in the dashboard, I made the class using python library....
I can make a object from python client no problem....

Is there a working Android example?

**Comment by MariuszWisniewski** [comment]
Sorry for the trouble @sirvon. For some reason actually older version of the lib is marked as the newest release, and using this old version (4.0.1) produces this error.

Could you please try 4.0.2 - https://github.com/Syncano/syncano-android/releases/tag/v4.0.2 ?

If that doesn't help, please also make sure that the class name and instance name is correct. If using correct instance/class name and version 4.0.2 doesn't help - let us know and we will dig deeper.

Adding @stasheq here, our Android lib dev, he will also try to help you and find any potential bugs.

**Comment by sirvon** [comment]
that just made my friday!
f@#$@# thx!!!

let the syncano games begin....!
