### ISSUE TITLE
publish on maven/etc...

### ISSUE THREAD

**Issue by sirvon** [Syncano/syncano-android#9]
can we get this lib published to use as a one liner in gradle??

thanks!

**Comment by stasheq** [comment]
Not yet, but it will be possible. Current plan is to publish it in the first half of January after next version release.

**Comment by sirvon** [comment]
:+1:

**Comment by mshusek** [comment]
Hi, version 4.0.5 is now available on jCenter and maven repository. Just add this line to your dependencies.

```
compile 'io.syncano:library:4.0.5'
```

**Comment by sirvon** [comment]
thank you! :+1:
